services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: always
  
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - backend