services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - ./postgres_db:/data/db
      - ./server/db/renshuu-db.dump:/docker-entrypoint-initdb.d/renshuu-db.dump
      - ./server/db/restore.sh:/docker-entrypoint-initdb.d/restore.sh:ro # read only
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    restart: always
    depends_on:
      db:
        condition: service_healthy
  
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend