/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

import { Route as rootRouteImport } from "./routes/__root";

const VocabularyLazyRouteImport = createFileRoute("/vocabulary")();
const ReviewedWordsLazyRouteImport = createFileRoute("/reviewed-words")();
const FlashcardsLazyRouteImport = createFileRoute("/flashcards")();
const IndexLazyRouteImport = createFileRoute("/")();

const VocabularyLazyRoute = VocabularyLazyRouteImport.update({
  id: "/vocabulary",
  path: "/vocabulary",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/vocabulary.lazy").then((d) => d.Route));
const ReviewedWordsLazyRoute = ReviewedWordsLazyRouteImport.update({
  id: "/reviewed-words",
  path: "/reviewed-words",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/reviewed-words.lazy").then((d) => d.Route));
const FlashcardsLazyRoute = FlashcardsLazyRouteImport.update({
  id: "/flashcards",
  path: "/flashcards",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/flashcards.lazy").then((d) => d.Route));
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route));

export interface FileRoutesByFullPath {
  "/": typeof IndexLazyRoute;
  "/flashcards": typeof FlashcardsLazyRoute;
  "/reviewed-words": typeof ReviewedWordsLazyRoute;
  "/vocabulary": typeof VocabularyLazyRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexLazyRoute;
  "/flashcards": typeof FlashcardsLazyRoute;
  "/reviewed-words": typeof ReviewedWordsLazyRoute;
  "/vocabulary": typeof VocabularyLazyRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexLazyRoute;
  "/flashcards": typeof FlashcardsLazyRoute;
  "/reviewed-words": typeof ReviewedWordsLazyRoute;
  "/vocabulary": typeof VocabularyLazyRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/flashcards" | "/reviewed-words" | "/vocabulary";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/flashcards" | "/reviewed-words" | "/vocabulary";
  id: "__root__" | "/" | "/flashcards" | "/reviewed-words" | "/vocabulary";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  FlashcardsLazyRoute: typeof FlashcardsLazyRoute;
  ReviewedWordsLazyRoute: typeof ReviewedWordsLazyRoute;
  VocabularyLazyRoute: typeof VocabularyLazyRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/vocabulary": {
      id: "/vocabulary";
      path: "/vocabulary";
      fullPath: "/vocabulary";
      preLoaderRoute: typeof VocabularyLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reviewed-words": {
      id: "/reviewed-words";
      path: "/reviewed-words";
      fullPath: "/reviewed-words";
      preLoaderRoute: typeof ReviewedWordsLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/flashcards": {
      id: "/flashcards";
      path: "/flashcards";
      fullPath: "/flashcards";
      preLoaderRoute: typeof FlashcardsLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FlashcardsLazyRoute: FlashcardsLazyRoute,
  ReviewedWordsLazyRoute: ReviewedWordsLazyRoute,
  VocabularyLazyRoute: VocabularyLazyRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
