/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const FlashcardsLazyImport = createFileRoute('/flashcards')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const FlashcardsLazyRoute = FlashcardsLazyImport.update({
  path: '/flashcards',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/flashcards.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/flashcards': typeof FlashcardsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/flashcards': typeof FlashcardsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/flashcards': typeof FlashcardsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flashcards'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flashcards'
  id: '__root__' | '/' | '/flashcards'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  FlashcardsLazyRoute: typeof FlashcardsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FlashcardsLazyRoute: FlashcardsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/flashcards"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/flashcards": {
      "filePath": "flashcards.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
